apiVersion: v1
kind: ConfigMap
metadata:
  name: blockchain-auth-config
  namespace: blockchain-auth
data:
  # URL RPC de la blockchain
  # Pour Minikube avec Hardhat local, utiliser host.minikube.internal
  BLOCKCHAIN_RPC_URL: "http://host.minikube.internal:8545"

  # Port du serveur
  PORT: "8080"
