apiVersion: v1
kind: Service
metadata:
  name: blockchain-auth-service
  namespace: blockchain-auth
  labels:
    app: blockchain-auth-server
spec:
  type: NodePort
  selector:
    app: blockchain-auth-server
  ports:
  - port: 8080
    targetPort: 8080
    protocol: TCP
    name: http
